version: '3.0'

networks:
  gacha_network:
    driver: bridge

services:
  db:
    image: postgres:14
    container_name: gacha-db
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env
    networks:
      - gacha_network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

  app:
    image: node:16
    container_name: gacha-api
    build: .
    ports:
      - 5001:5000
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - gacha_network
    volumes:
      - .:/usr/src/
